---
    name: Build and Push Image to AWS ECR

    on:
      workflow_dispatch:
    env:
      AWS_REGION: ap-south-1 
      IMAGE_TAG: img tag                
      ECS_SERVICE: ecs service name               
      ECS_CLUSTER: cluster name                 
      ECS_TASK_DEFINITION_FAMILY: task name
      CONTAINER_NAME: container name 


    jobs:
      build-and-push:
        name: Build and Push to ECR
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
    
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
            aws-region: ${{ env.AWS_REGION }}
    
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1
    
        - name: Build, Tag, and Push the Image to Amazon ECR
          id: build-image
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: repo_name
            IMAGE_TAG: ${{ env.IMAGE_TAG }}
          run: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG